#! /usr/bin/env python

import argparse
import logging
from simplemail.mandamail import inviamail

# ***** CONFIG ******
MAILFROM = 'me@example.com'
MAILTO = ['you@example.com']
SERVER = 'smtp.server.com:port'
USERNAME = 'myusername'
PASSWORD = 'mypassword'

# ***** END CONFIG ******


# ***** logging module objects and definition *****

LOGFORMAT_STDOUT = { logging.DEBUG: '%(module)s:%(funcName)s:%(lineno)s - %(levelname)-8s: %(message)s',
             logging.INFO: '%(levelname)-8s: %(message)s',
             logging.WARNING: '%(levelname)-8s: %(message)s',
             logging.ERROR: '%(levelname)-8s: %(message)s',
             logging.CRITICAL: '%(levelname)-8s: %(message)s'
           }

LOGFORMAT_FILE = { logging.DEBUG: "%(module)s:%(funcName)s:%(lineno)s - ***%(levelname)s***: %(message)s",
           logging.INFO: "%(asctime)s ***%(levelname)s***: %(message)s",
           logging.WARNING: "%(asctime)s ***%(levelname)s***: [%(module)s:%(funcName)s] %(message)s",
           logging.ERROR: "%(asctime)s *****%(levelname)s*****: ***[%(module)s:%(funcName)s:%(lineno)s]*** ***%(message)s***",
           logging.CRITICAL: "%(asctime)s *****%(levelname)s*****: ***[%(module)s:%(funcName)s:%(lineno)s]*** ***%(message)s***"
         }

LOGDATEFMT = '%Y-%m-%d %H:%M:%S'

class NullHandler(logging.Handler):
    def emit(self, record):
        pass

class Formattatore(logging.Formatter):
    def format(self, record):
        self._fmt=LOGFORMAT_FILE[record.levelno]
        s = logging.Formatter.format(self,record)
        #super(Formattatore, self).format(record)
        return s
        
# ***** END logging module *****

# --- root logger
rootlogger = logging.getLogger()
rootlogger.setLevel(logging.DEBUG)

lvl_config_logger = logging.INFO

console = logging.StreamHandler()
console.setLevel(lvl_config_logger)

formatter = logging.Formatter(LOGFORMAT_STDOUT[lvl_config_logger])
console.setFormatter(formatter)

rootlogger.addHandler(console)

parser = argparse.ArgumentParser(description='Send the analysis result')
parser.add_argument('-f', dest='files', metavar='file', type=str, nargs='+', 
                    help='files to send')
parser.add_argument('-m', dest='message', type=str, help='message to send',
                    default='I am sendind this e-mail for osmose')
parser.add_argument('-s', dest='subject', type=str, help='subject of the mail',
                    default='Mail sent with mail.py')

###FIXME 
# parser.add_argument('-t', dest='to', type=str, help='destination of the mail',
#                     default='something')
# parser.add_argument('--format', type=str, help='format of the mail',
#                     default='plaintext')


args = parser.parse_args()

inviamail(app='osmose',
          mailfrom=MAILFROM,
          mailto=MAILTO, 
          files=args.files,
          cc=None, 
          bcc=None,
          server = SERVER,
          auth_required=True,
          username= USERNAME,
          password= PASSWORD,
          subject=args.subject,
          mail_format='plaintext',
          html_text=None,
          plaintext_text=args.message,
          blacklist=None, 
          passwd_force_ask=False, 
          dry_send=False)    